/**
 * L8ZK SDK Type Definitions
 * Privacy-preserving verifiable credentials using zero-knowledge proofs
 */

/** Supported credential formats */
export type CredentialFormat = "sd-jwt" | "mdl";

/** EC public key in JWK format (P-256) */
export interface ECPublicKey {
    kty: "EC";
    crv: "P-256";
    x: string;
    y: string;
    kid?: string;
}

/** EC private key in JWK format (P-256) */
export interface ECPrivateKey extends ECPublicKey {
    d: string;
}

/** Device binding configuration */
export interface DeviceBindingConfig {
    /** Private key for signing (hex or Uint8Array) */
    privateKey: Uint8Array | string;
    /** Public key in JWK format */
    publicKey: ECPublicKey;
}

/** Options for preparing a credential */
export interface PrepareOptions {
    /** Raw SD-JWT credential string */
    credential: string;
    /** Credential format (defaults to 'sd-jwt') */
    format?: CredentialFormat;
    /** Enable device binding (binds credential to device secure element) */
    deviceBinding?: boolean | DeviceBindingConfig;
    /** Issuer public key (auto-extracted from credential if not provided) */
    issuerPublicKey?: ECPublicKey;
    /** Custom storage key for persistence */
    storageKey?: string;
}

/** Predicate operators for policy conditions */
export type PredicateOperator =
    | "eq"
    | "neq"
    | "gt"
    | "gte"
    | "lt"
    | "lte"
    | "in"
    | "nin";

/** Single predicate condition */
export interface PredicateCondition {
    /** Greater than or equal */
    gte?: number;
    /** Greater than */
    gt?: number;
    /** Less than or equal */
    lte?: number;
    /** Less than */
    lt?: number;
    /** Equal to */
    eq?: string | number | boolean;
    /** Not equal to */
    neq?: string | number | boolean;
    /** Value is in set */
    in?: (string | number)[];
    /** Value is not in set */
    nin?: (string | number)[];
}

/** Policy definition for selective disclosure */
export interface Policy {
    /** Age-related predicates */
    age?: PredicateCondition;
    /** Country code predicates */
    countryCode?: string | PredicateCondition;
    /** Nationality predicates */
    nationality?: string | PredicateCondition;
    /** Custom attribute predicates */
    [attribute: string]:
        | string
        | number
        | boolean
        | PredicateCondition
        | undefined;
}

/** Options for generating a proof (show phase) */
export interface ShowOptions {
    /** Verifier's policy requirements */
    policy: Policy;
    /** Fresh nonce from verifier (prevents replay attacks) */
    nonce: string;
    /** Current date override (for testing) */
    currentDate?: { year: number; month: number; day: number };
}

/** Prepared credential handle returned by OpenAC.prepare() */
export interface CredentialHandle {
    /** Unique identifier for this prepared credential */
    id: string;
    /** Generate a proof for the given policy */
    show(options: ShowOptions): Promise<Proof>;
    /** Get credential metadata without revealing sensitive data */
    getMetadata(): CredentialMetadata;
    /** Revoke/delete this prepared credential from storage */
    revoke(): Promise<void>;
}

/** Metadata about a prepared credential */
export interface CredentialMetadata {
    /** Credential format */
    format: CredentialFormat;
    /** Issuer identifier (DID or URL) */
    issuer: string;
    /** Subject identifier if present */
    subject?: string;
    /** Issuance timestamp */
    issuedAt?: Date;
    /** Expiration timestamp */
    expiresAt?: Date;
    /** Available claim types (not values) */
    availableClaims: string[];
    /** Whether device binding is enabled */
    deviceBound: boolean;
}

/** Zero-knowledge proof generated by show() */
export interface Proof {
    /** Prepare phase proof (reblinded) */
    prepareProof: Uint8Array;
    /** Show phase proof */
    showProof: Uint8Array;
    /** Shared commitment linking prepare and show proofs */
    sharedCommitment: Uint8Array;
    /** Policy that was proven */
    policy: Policy;
    /** Nonce used in this proof */
    nonce: string;
    /** Timestamp of proof generation */
    timestamp: number;
    /** Protocol version */
    version: string;
}

/** Serialized proof for transmission */
export interface SerializedProof {
    /** Base64-encoded prepare proof */
    prepareProof: string;
    /** Base64-encoded show proof */
    showProof: string;
    /** Base64-encoded shared commitment */
    sharedCommitment: string;
    /** Policy proven */
    policy: Policy;
    /** Nonce */
    nonce: string;
    /** Timestamp */
    timestamp: number;
    /** Version */
    version: string;
}

/** Verification result */
export interface VerificationResult {
    /** Whether the proof is valid */
    valid: boolean;
    /** Error message if invalid */
    error?: string;
    /** Verified policy conditions */
    verifiedPolicy?: Policy;
    /** Proof timestamp */
    timestamp?: number;
}

/** Options for verification */
export interface VerifyOptions {
    /** Expected policy (must match proof's policy) */
    expectedPolicy?: Policy;
    /** Maximum age of proof in milliseconds */
    maxProofAge?: number;
    /** Expected nonce */
    expectedNonce?: string;
}

/** Storage adapter interface for cross-platform persistence */
export interface StorageAdapter {
    get(key: string): Promise<Uint8Array | null>;
    set(key: string, value: Uint8Array): Promise<void>;
    delete(key: string): Promise<void>;
    keys(): Promise<string[]>;
}

/** SDK configuration options */
export interface OpenACConfig {
    /** Custom storage adapter (defaults to IndexedDB in browser, AsyncStorage in RN) */
    storage?: StorageAdapter;
    /** Path to WASM module (for custom deployments) */
    wasmPath?: string;
    /** Enable debug logging */
    debug?: boolean;
}

/** Internal prepared state stored for reblinding */
export interface PreparedState {
    /** Credential ID */
    id: string;
    /** Original credential (encrypted) */
    encryptedCredential: Uint8Array;
    /** Prepare proof */
    prepareProof: Uint8Array;
    /** Prepare instance */
    prepareInstance: Uint8Array;
    /** Prepare witness */
    prepareWitness: Uint8Array;
    /** Shared blinds for linking */
    sharedBlinds: Uint8Array;
    /** Device binding key (if enabled) */
    deviceKey?: ECPrivateKey;
    /** Credential metadata */
    metadata: CredentialMetadata;
    /** Extracted claims for show circuit */
    claims: ExtractedClaims;
    /** Creation timestamp */
    createdAt: number;
}

/** Extracted claims from credential */
export interface ExtractedClaims {
    /** Device binding public key X coordinate */
    keyBindingX: bigint;
    /** Device binding public key Y coordinate */
    keyBindingY: bigint;
    /** Decoded age claim bytes */
    ageClaim: number[];
    /** Raw claim data for predicates */
    rawClaims: Map<string, unknown>;
}

/** Circuit parameters matching circom configuration */
export interface CircuitParams {
    maxMessageLength: number;
    maxB64PayloadLength: number;
    maxMatches: number;
    maxSubstringLength: number;
    maxClaimsLength: number;
}

/** Default circuit parameters (from circuits.json) */
export const DEFAULT_CIRCUIT_PARAMS: CircuitParams = {
    maxMessageLength: 1920,
    maxB64PayloadLength: 1900,
    maxMatches: 4,
    maxSubstringLength: 50,
    maxClaimsLength: 128,
};
